name: TelegramChatLogger
version: 1.2
main: cloud.stivenfocs.TelegramChatLogger.Loader
authors: [StivenFocs]
api-version: 1.8
description: "This plugin provide a simple tool for server staff lie moderators to log and read the ingame chat from a private liked telegram group or channel."
commands:
    telegramchatlogger:
        aliases: [tglogger]
        permission: tglogger.admin
permissions:
    tglogger.admin:
        default: op